basePath: /
host: localhost:8080
info:
  contact: {}
  description: Ini adalah API untuk Task Management System.
  title: Task Management System API
  version: "1.0"
paths:
  /ping:
    get:
      description: Menguji dengan menjalankan ping ke API
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping apa
      tags:
      - ping
swagger: "2.0"
